### ISSUE TITLE
error compail

### ISSUE THREAD

**Issue by rdilley-usgs** [USGS-EROS/espa-product-formatter#9]
```
What steps will reproduce the problem?
1. when I do command "make" on bash

What is the expected output? What do you see instead?

make[1]: *** [envi_header.o] Error 1
make[1]: Leaving directory `/home/kuncoro/releases/version_1.3.1/src/raw_binary/io_libs'
make all in format_conversion_libs...
make[1]: Entering directory `/home/kuncoro/releases/version_1.3.1/src/raw_binary/format_conversion_libs'
gcc -Wall -g -I -I../common -I../io_libs -I -I -I -I -I -I -c convert_lpgs_to_espa.c
In file included from convert_lpgs_to_espa.c:26:0:
convert_lpgs_to_espa.h:28:27: fatal error: error_handler.h: No such file or directory
 #include "error_handler.h"
                           ^
compilation terminated.


What version of the product are you using? On what operating system?

v.1.3.1
Ubuntu 14.01


Please provide any additional information below.

I have download and install to /usr/local/ all these libraries
hdf4-2.11
hdfeos2.17.v100
libtiff
libgeotiff
szip
zlib
proj-4.8






```

Original issue reported on code.google.com by `jokam313` on 2015-03-13 03:52:23

**Comment by tonal** [comment]
Need define ESPAINC env variable
```
$ export ESPAINC=/media/tonal/my_book/lang/work/Space/espa-product-formatter/src/raw_binary/include
```

**Comment by gschmidt-usgs** [comment]
The README for espa-product-formatter contains the installation information.  It identified the libraries needed to build this software along with the environment variables needed to be defined.

**Comment by wessm** [comment]
Since yesterday I have the same issue, although it worked before and all the ENV variables including ESPAINC and ESPALIB are set. Maybe somebody has an idea what could be wrong?

**Comment by wessm** [comment]
I found out that the gcc -I command only works with multiple directories if they are all set, so you cannot add libraries one by one, because if multiple directories are included via gcc -I<dir1> -I<dir2>, dir2 is ignored if dir1 is not set. Working now!

**Comment by tgirgin23** [comment]
Could you please give more information on the steps that you did to fix the problem? I am having the same issue as the author of this post, and can't seem to be able to fix it right now. All the files are where the should be, however "raw_binary_io.h" and "espa_metadata.h" cannot be found.

**Comment by tgirgin23** [comment]
Alright, I figured out what @wessm was saying. I had to go and manually change the -I values set to the environment variables. Even though I have set my environment variables correctly, the Makefiles (each one) could not figure them out.
When running "make", I would get error similar to this one:

`gcc -g -Wall -O2  -I../include **-I -I -I** -c generate_land_water_mask.c -o generate_land_water_mask.o`

As you can see, the first -I is correctly being displayed because it is just implemented directly in the Makefile. However, once the Makefile calls for a environment variable, it does not seem to be able to interpret them and leaves those parameters empty. Here is an example:

`INCS = -I**$(XML2INC)** -I../include -I../io_libs`

Replacing the XML2INC variable with the path where you have your libxml2 installed (e.g., /usr/include/libxml2") will correctly build the files. Here is what worked for me:

`INCS = **-I/usr/include/libxml2** -I../include -I../io_lib`

**Comment by ronaldddilley** [comment]
Odd.  I don't know why one would have to hard code those if the environment is setup correctly.
But in any case, we have revamped the Makefiles for the next release March2016, to bring them inline with the rest of our science applications.
Maybe all of those issues will go away.

**Comment by tgirgin23** [comment]
@ronaldddilley I am unsure as to why this is happening too. But when I look at my systems environment variables, they are all setup correctly. Just so you know, I am running Ubuntu Wily (15.10).

I finally got make to build the files. However, the system still does not recognize the prefix variable and I can therefore not make install. Is there any way I can change the prefix variable manually somewhere?

**Comment by tgirgin23** [comment]
Never mind. I found out that I could change it from the src/raw_binary/tools/Makefile. Also had to change some install variables from the src/raw_binary/Makefile. I believe everything is correctly installed now. 
Thank you for the help!
